<?php

/**
 * @file
 */

use Drupal\tac_services\Service\TacGlobalConfigService;
use Drupal\tac_services\Service\TacServicesConfManager;

/**
 * Implements hook_preprocess_page
 */
function tac_services_preprocess_page(&$variables)
{
  $confManager = \Drupal::service(TacServicesConfManager::SERVICE_NAME);
  $services = $confManager->getTacServicesConf();

  $activeServices = [];

  if(!empty($services)){
    foreach ($services as $pluginId => $service) {
      if ($service['is_active']) {
        $activeServices[$pluginId] = $service;
      }
    }
  }
  $variables['activeServices'] = $activeServices;
}

/**
 * Implements hook_page_attachments().
 */
function tac_services_page_attachments(array &$attachments) {
  $is_admin = \Drupal::service('router.admin_context')->isAdminRoute();
  if (!$is_admin) {
    /** @var TacServicesConfManager $confManager */
    $confManager = \Drupal::service(TacServicesConfManager::SERVICE_NAME);
    $services = $confManager->getTacServicesConf();
    if (!empty($services)) {
      $activeServices = [];
      foreach ($services as $pluginId => $service) {
        if ($service['is_active']) {
          $activeServices[$pluginId] = $service;
        }
      }

      if (!empty($activeServices)) {
        // Ajout des variables globales de tarteaucitron.js dans drupalSettings.
        /** @var TacGlobalConfigService $globalTacConfService */
        $globalTacConfService = \Drupal::service(TacGlobalConfigService::SERVICE_NAME);
        $globalConfValues = $globalTacConfService->getAllValues();

        // On ajoute le path du module tac_services pour lier les fihchiers de traduction.
        $attachments['#attached']['drupalSettings']['tacServices']['translation_rep'] = '/' . drupal_get_path('module', 'tac_services').'/libraries/tarteaucitron/';

        $attachments['#attached']['drupalSettings']['tacServices']['globalSettings'] = [
          // Privacy Policy URL
          $globalTacConfService::PRIVACY_URL          => $globalConfValues[$globalTacConfService::PRIVACY_URL],

          $globalTacConfService::SCROLLING_BEHAVIOR   => ($globalConfValues[$globalTacConfService::SCROLLING_BEHAVIOR]) ? TRUE : FALSE,

          $globalTacConfService::CUSTOM_DISCLAIMER    => t($globalConfValues[$globalTacConfService::CUSTOM_DISCLAIMER]),

          $globalTacConfService::HIGH_PRIVACY         => ($globalConfValues[$globalTacConfService::HIGH_PRIVACY]) ? TRUE : FALSE,
          $globalTacConfService::ALLOWED_BUTTON       => ($globalConfValues[$globalTacConfService::ALLOWED_BUTTON]) ? TRUE : FALSE,
          $globalTacConfService::COOKIE_LIST          => ($globalConfValues[$globalTacConfService::COOKIE_LIST]) ? TRUE : FALSE,
          $globalTacConfService::SHOW_ALERT_SMALL     => ($globalConfValues[$globalTacConfService::SHOW_ALERT_SMALL]) ? TRUE : FALSE,
          $globalTacConfService::ADBLOCKER            => ($globalConfValues[$globalTacConfService::ADBLOCKER]) ? TRUE : FALSE,

          // ACCCEPT & DENY
          $globalTacConfService::ACCEPT_ALL_CTA       => ($globalConfValues[$globalTacConfService::ACCEPT_ALL_CTA]) ? TRUE : FALSE,
          $globalTacConfService::DENY_ALL_CTA         => ($globalConfValues[$globalTacConfService::DENY_ALL_CTA]) ? TRUE : FALSE,

          // First time Banner position
          $globalTacConfService::ORIENTATION          => $globalConfValues[$globalTacConfService::ORIENTATION],

          $globalTacConfService::HANDLE_DNT_REQUEST   => ($globalConfValues[$globalTacConfService::HANDLE_DNT_REQUEST]) ? TRUE : FALSE,

          $globalTacConfService::MANDATORY            => ($globalConfValues[$globalTacConfService::MANDATORY]) ? TRUE : FALSE,

          // Icon
          $globalTacConfService::SHOW_ICON            => ($globalConfValues[$globalTacConfService::SHOW_ICON]) ? TRUE : FALSE,
          $globalTacConfService::ICON_POSITION        => $globalConfValues[$globalTacConfService::ICON_POSITION],
          $globalTacConfService::ICON_SOURCE        => $globalConfValues[$globalTacConfService::ICON_SOURCE],

          //Cookies Duration
          $globalTacConfService::COOKIES_DURATION     => ($globalConfValues[$globalTacConfService::COOKIES_DURATION]),
        ];

        // Ajout de la library tarte au citron.
        $attachments['#attached']['library'][] = 'tac_services/tac_services';
        // Ajout des libraries de tout les services.
        foreach ($activeServices as $pluginId => $service) {
          $attachments['#attached']['library'][] = $service['library'];
          if (!empty($service['data'])) {
            foreach ($service['data'] as $key => $value) {
              $attachments['#attached']['drupalSettings']['tacServices'][$pluginId][$key] = $value;
            }
          }
        }
      }
    }
    return;
  }

}
