<?php 

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;


/**
 * Implements hook_ENTITY_TYPE_view()
 */

function hello_world_node_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode) {
        $build['awesome'] = [
            '#markup'=>'<h1>Hello World</h1>',
            '#allowed_tags'=>['h1'],      
        ];
}